aosp.dependencies: Change sony-common branch to r-mr1
device-sony-common master branch now has some WIP for bringing up Edo support that for now breaks
every other device due to HAL imcompatibility.
r-mr1 branch on the other hands is for Android R but doesnt have those changes.
Switch the branch from master to r-mr1 to fix build.

error: https://pastebin.com/H2vXtMjb